import React from 'react'

const Csr = () => {
    return (
        <div className='myBackground mt-[-4rem] md:p-24 p-8 md:pt-6 '>
            <div style={{ maxWidth: '50rem', margin: '0 auto' }} className='bg-[#0c203d83] p-12'>
                <h4 style={{ boxSizing: 'border-box', fontFamily: 'josefin_sansregular', fontWeight: 500, lineHeight: '1.1', marginTop: 10, marginBottom: 10, fontSize: 18 }}><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}><strong style={{ boxSizing: 'border-box', fontWeight: 'bold' }}>Community Engagement</strong></span></h4>
                <p style={{ boxSizing: 'border-box', margin: '0px 0px 10px', fontFamily: 'josefin_sansregular', fontSize: 15 }}><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}>As a Responsible Industry member and Corporate Citizen, Mechtra INDIA always believes in giving back to the society. At Mechtra INDIA, commitment to enable community engagement and environmental initiatives is achieved through well-outlined goals related to sustainability, against which all results are measured. These objectives encompass a wide framework for consistent business growth, taking into consideration all interest of our stakeholders.</span></p>
                <p style={{ boxSizing: 'border-box', margin: '0px 0px 10px', fontFamily: 'josefin_sansregular', fontSize: 15 }}><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}>Our CSR wing, Suman Nirmal Minda Charitable Trust runs project that are long term, ongoing and sustainable to serve the community in a best possible manner, with an approach to encourage, educate and empower people to bring about a positive change. All projects are being implemented as per the defined thematic areas of the Group:</span></p>
                <ol style={{ boxSizing: 'border-box', margin: 0, padding: 0, listStyleType: 'none', fontFamily: 'josefin_sansregular', fontSize: 15 }}>
                    <li style={{ boxSizing: 'border-box', padding: '5px 0px', fontSize: 16, lineHeight: '19.2px', listStyleType: 'disc' }}><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}>Education</span></li>
                    <li style={{ boxSizing: 'border-box', padding: '5px 0px', fontSize: 16, lineHeight: '19.2px', listStyleType: 'disc' }}><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}>Skill Development</span></li>
                    <li style={{ boxSizing: 'border-box', padding: '5px 0px', fontSize: 16, lineHeight: '19.2px', listStyleType: 'disc' }}><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}>Preventive Healthcare</span></li>
                    <li style={{ boxSizing: 'border-box', padding: '5px 0px', fontSize: 16, lineHeight: '19.2px', listStyleType: 'disc' }}><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}>Environment Sustainability</span></li>
                    <li style={{ boxSizing: 'border-box', padding: '5px 0px', fontSize: 16, lineHeight: '19.2px', listStyleType: 'disc' }}><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}>Community Well-Being</span></li>
                </ol>
                <p style={{ boxSizing: 'border-box', margin: '0px 0px 10px', fontFamily: 'josefin_sansregular', fontSize: 15 }}><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}>Since more than two decades, the Group is formally and strategically involved in social initiatives, and started Minda Bal Gram and community school to provide education, shelter, medical facilities and food to underprivileged children. With time, in year 2012, the Group inaugurated Samarth-Jyoti, with a vision to enable and empower underprivileged youth and women with required skill sets to live life with dignity and happiness under the able leadership of and guidance of Mrs. Suman Minda, Chairperson and President, SUMAN NIRMAL MINDA CHARITABLE TRUST and Shri Nirmal Kumar Minda, CMD, Mechtra INDIA Group.</span></p>
                <h4 style={{ boxSizing: 'border-box', fontFamily: 'josefin_sansregular', fontWeight: 500, lineHeight: '1.1', marginTop: 10, marginBottom: 10, fontSize: 18 }}><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}><strong style={{ boxSizing: 'border-box', fontWeight: 'bold' }}>Samarth Jyoti:</strong></span></h4>
                <p style={{ boxSizing: 'border-box', margin: '0px 0px 10px', fontFamily: 'josefin_sansregular', fontSize: 15 }}><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}>The project Samarth-Jyoti runs under the aegis of our trust- SUMAN NIRMAL MINDA CHARITABLE TRUST, registered under Societies Registration Act, 1860. There are various activities tailored to engage and empower deprived people from the communities through education, vocational training and need based community interventions.</span></p>
                <p style={{ boxSizing: 'border-box', margin: '0px 0px 10px', fontFamily: 'josefin_sansregular', fontSize: 15 }}><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}>The Samarth-Jyoti centres also facilitate the community students who are from economically weaker background with formal education in form of community school for primary children and remedial classes to support the students to main stream into regular education. Students from our centres bridge their academic gap and enrol themselves in government schools for future education.</span></p>
                <p style={{ boxSizing: 'border-box', margin: '0px 0px 10px', fontFamily: 'josefin_sansregular', fontSize: 15 }}><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}>We provide various vocational trainings at our Samarth-Jyoti Centres in order to hone skills in the field of Cutting &amp; Tailoring, Beauty Culture and IT Literacy courses. All courses are accredited by approved government agencies. The duration of the courses are 6 months which provide target beneficiaries with a platform to acquire new skills and provide them access to adequate employment opportunities to gain socio-economic independency.</span></p>
                <h4 style={{ boxSizing: 'border-box', fontFamily: 'josefin_sansregular', fontWeight: 500, lineHeight: '1.1', marginTop: 10, marginBottom: 10, fontSize: 18 }}><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}><strong style={{ boxSizing: 'border-box', fontWeight: 'bold' }}>The Suman Nirmal Minda School</strong></span></h4>
                <p style={{ boxSizing: 'border-box', margin: '0px 0px 10px', fontFamily: 'josefin_sansregular', fontSize: 15 }}><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}><strong style={{ boxSizing: 'border-box', fontWeight: 'bold' }}>The Suman Nirmal Minda Charitable Trust</strong>&nbsp;also initiated a Senior Secondary School project;&nbsp;<strong style={{ boxSizing: 'border-box', fontWeight: 'bold' }}>The Suman Nirmal Minda School</strong>&nbsp;between Vithalapur and Kadi, Gujarat. This is a senior secondary school affiliated to CBSE to provide value based quality education, benefiting maximum people. The vision is to fosters academic excellence, leadership skills and social values in an enabling environment to support children to be socially responsible citizens of tomorrow Total capacity of the school is to serve more than 1500 plus students and currently 400 students are getting education.</span></p>
                <p style={{ boxSizing: 'border-box', margin: '0px 0px 10px', fontFamily: 'josefin_sansregular', fontSize: 15 }}><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}>Suman Nirmal Minda Charitable Trust also support and facilitate projects running under Moga Devi Minda Charitable Trust (MDMCT) with various educational and healthcare facilities such as:</span></p>
                <p style={{ boxSizing: 'border-box', margin: '0px 0px 10px', fontFamily: 'josefin_sansregular', fontSize: 15 }}><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}><strong style={{ boxSizing: 'border-box', fontWeight: 'bold' }}>1. Moga Devi Minda Memorial School</strong>&nbsp;is established in 2010. It is spread over 6 acres and is affiliated to CBSE. It provides holistic learning environment and encourages creative thinking. The School is a Senior Secondary, Co- education school with more than 1200 students. School caters to provide high quality education in rural areas with excellent facilities.</span><br style={{ boxSizing: 'border-box' }} /><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}><a style={{ boxSizing: 'border-box', color: 'rgb(51, 122, 183)', textDecorationLine: 'none', backgroundPosition: '0px 0px', outlineWidth: 0 }} href="https://www.mindaschool.com/" rel="noreferrer"  target="_blank" >For more information click here</a></span></p>
                <p style={{ boxSizing: 'border-box', margin: '0px 0px 10px', fontFamily: 'josefin_sansregular', fontSize: 15 }}><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}><strong style={{ boxSizing: 'border-box', fontWeight: 'bold' }}>2. Shadi Lal Minda Memorial Hospital</strong>&gt; was inaugurated in 2016 at Bagla, Hisar by Honorable Chief Minister, Manohar Lal ji. It’s a 100 bedded, multispecialty hospital with all modern amenities, facilities and specialized doctors to support rural people.</span></p>
                <p style={{ boxSizing: 'border-box', margin: '0px 0px 10px', fontFamily: 'josefin_sansregular', fontSize: 15 }}><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}><strong style={{ boxSizing: 'border-box', fontWeight: 'bold' }}>3. S.L Minda Skill centre</strong>&nbsp;was established in 2007 to provide vocational training to rural people.</span></p>
                <p style={{ boxSizing: 'border-box', margin: '0px 0px 10px', fontFamily: 'josefin_sansregular', fontSize: 15 }}><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}><strong style={{ boxSizing: 'border-box', fontWeight: 'bold' }}>4. S.L Minda Sewa Sadan</strong>&nbsp;was established in 2007 to provide community space to village folks to hold meetings, social, religious functions and get-together.</span></p>
                <p style={{ boxSizing: 'border-box', margin: '0px 0px 10px', fontFamily: 'josefin_sansregular', fontSize: 15 }}><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}>Along with above mentioned initiatives, SNMCT and MDMCT are also associated with various programs in alignment to our thematic areas to educate, encourage and empower our communities for overall societal development and growth.</span></p>
                <h4 style={{ boxSizing: 'border-box', fontFamily: 'josefin_sansregular', fontWeight: 500, lineHeight: '1.1', marginTop: 10, marginBottom: 10, fontSize: 18 }}><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}><strong style={{ boxSizing: 'border-box', fontWeight: 'bold' }}>Presences:</strong></span></h4>
                <p style={{ boxSizing: 'border-box', margin: '0px 0px 10px', fontFamily: 'josefin_sansregular', fontSize: 15 }}><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}>We have been working in 7 states with 15 Samarth-Jyoti centres. In addition to this two senior secondary school and hospital is functional in Gujarat and Haryana, India respectively.</span></p>
                <p style={{ boxSizing: 'border-box', margin: '0px 0px 10px', fontFamily: 'josefin_sansregular', fontSize: 15 }}><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}><img style={{ boxSizing: 'border-box', borderWidth: 0, verticalAlign: 'middle', maxWidth: '100%' }} src="https://www.unominda.com/uploads/CSR/csr.jpg" width="100%" /></span></p>
                <p style={{ boxSizing: 'border-box', margin: '0px 0px 10px', fontFamily: 'josefin_sansregular', fontSize: 15 }}><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}><a style={{ boxSizing: 'border-box', color: 'rgb(51, 122, 183)', textDecorationLine: 'none', backgroundPosition: '0px 0px', outlineWidth: 0 }} href="https://www.unominda.com/images/csr/Minda-CSR-2016.pdf" target="_blank" rel="noopener noreferrer">Download CSR Report 2016-17</a></span><br style={{ boxSizing: 'border-box' }} /><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}><a style={{ boxSizing: 'border-box', color: 'rgb(51, 122, 183)', textDecorationLine: 'none', backgroundPosition: '0px 0px', outlineWidth: 0 }} href="https://www.unominda.com/uploads/CSR/Minda%20Low%20Res%20Final.pdf" rel="noreferrer" target="_blank" >Download CSR Report 2017-18</a></span><br style={{ boxSizing: 'border-box' }} /><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}><a style={{ boxSizing: 'border-box', color: 'rgb(51, 122, 183)', textDecorationLine: 'none', backgroundPosition: '0px 0px', outlineWidth: 0 }} href="https://www.unominda.com/uploads/CSR/Minda%20CSR%207Jan20.pdf" rel="noreferrer" target="_blank" >Download CSR Report 2018-19</a></span><br style={{ boxSizing: 'border-box' }} /><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}><a style={{ boxSizing: 'border-box', color: 'rgb(51, 122, 183)', textDecorationLine: 'none', backgroundPosition: '0px 0px', outlineWidth: 0 }} href="https://www.unominda.com/uploads/CSR/csr-annual-report-fy-2019-20.pdf" rel="noreferrer" target="_blank" >Download CSR Report 2019-20</a></span><br style={{ boxSizing: 'border-box' }} /><span style={{ fontSize: '14pt', fontFamily: 'arial, helvetica, sans-serif' }}><a style={{ boxSizing: 'border-box', color: 'rgb(51, 122, 183)', textDecorationLine: 'none', backgroundPosition: '0px 0px', outlineWidth: 0 }} href="https://www.unominda.com/uploads/Investor/2022/csr-annual-report-fy-2020-21.pdf" target="_blank" rel="noreferrer">Download CSR Report 2020-21</a></span></p>
            </div>
        </div>

    )
}

export default Csr