import React from 'react'

const privacy = () => {
    return (
        <div className="md:p-12 p-2 mt-32" style={{background: '#0a192f'}}>
  <p><span style={{color: 'rgb(0, 0, 0)', fontFamily: '"Times New Roman"', fontSize: 'medium', float: 'none', display: 'inline'}}>&nbsp; &nbsp; &nbsp;</span></p>
  <div style={{color: 'rgb(0, 0, 0)', fontFamily: '"Times New Roman"', fontSize: 'medium'}}><span style={{color: 'rgb(206, 212, 217)'}}><strong><span style={{fontSize: 26}}><span style={{fontSize: 26}} data-custom-class="title">PRIVACY NOTICE</span></span></strong></span></div>
  <div style={{color: 'rgb(0, 0, 0)', fontFamily: '"Times New Roman"', fontSize: 'medium'}}>&nbsp;</div>
  <div style={{color: 'rgb(0, 0, 0)', fontFamily: '"Times New Roman"', fontSize: 'medium'}}><span style={{color: 'rgb(198, 198, 198)'}}><strong><span style={{fontSize: 15}}><span style={{fontSize: 14}} data-custom-class="subtitle">Last updated&nbsp;May 23, 2022</span></span></strong></span></div>
  <div style={{color: 'rgb(0, 0, 0)', fontFamily: '"Times New Roman"', fontSize: 'medium'}}>&nbsp;</div>
  <div style={{color: 'rgb(0, 0, 0)', fontFamily: '"Times New Roman"', fontSize: 'medium'}}>&nbsp;</div>
  <div style={{color: 'rgb(0, 0, 0)', fontFamily: '"Times New Roman"', fontSize: 'medium'}}>&nbsp;</div>
  <div style={{color: 'rgb(0, 0, 0)', fontFamily: '"Times New Roman"', fontSize: 'medium', lineHeight: '1.5'}}><span style={{color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 15}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">This privacy notice for&nbsp;Mectra India&nbsp;(&quot;<strong style={{fontSize: 14, fontFamily: 'Arial'}}>Company</strong>,&quot; &quot;<strong style={{fontSize: 14, fontFamily: 'Arial'}}>we</strong>,&quot; &quot;<strong style={{fontSize: 14, fontFamily: 'Arial'}}>us</strong>,&quot; or &quot;<strong style={{fontSize: 14, fontFamily: 'Arial'}}>our</strong>&quot;</span><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">), describes how and why we might collect, store, use, and/or share (&quot;<strong style={{fontSize: 14, fontFamily: 'Arial'}}>process</strong>&quot;) your information when you use our services (&quot;<strong style={{fontSize: 14, fontFamily: 'Arial'}}>Services</strong>&quot;), such as when you:</span></span></span></div>
  <ul style={{color: 'rgb(0, 0, 0)', fontFamily: '"Times New Roman"', fontSize: 'medium'}}>
    <li style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">Visit our website&nbsp;at&nbsp;mectraindia.com<span style={{fontSize: 15, fontFamily: 'Arial'}}><span style={{fontSize: 14, fontFamily: 'Arial'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><span style={{fontSize: 15, fontFamily: 'Arial'}}><span style={{fontSize: 14, fontFamily: 'Arial'}}>, or any website of ours that links to this privacy notice</span></span></span></span></span></span></span></li>
  </ul>
  <div style={{color: 'rgb(0, 0, 0)', fontFamily: '"Times New Roman"', fontSize: 'medium'}}>
    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
    <ul>
      <li style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">Engage with us in other related ways, including any sales, marketing, or events</span></span></li>
    </ul>
    <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15}}><span style={{color: 'rgb(127, 127, 127)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><span style={{color: 'rgb(198, 198, 198)'}}><strong style={{fontSize: 14, fontFamily: 'Arial'}}>Questions or concerns?&nbsp;</strong>Reading this privacy notice will help you understand your privacy rights and choices. If you do not agree with our policies and practices, please do not use our Services. If you still have any questions or concerns, please contact us at&nbsp;support@mectraindia.com</span>.</span></span></span></div>
    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
    <div style={{lineHeight: '1.5'}}><span style={{color: 'rgb(206, 212, 217)'}}><strong><span style={{fontSize: 15}}><span style={{fontSize: 19}} data-custom-class="heading_1">SUMMARY OF KEY POINTS</span></span></strong></span></div>
    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
    <div style={{lineHeight: '1.5'}}><span style={{color: 'rgb(206, 212, 217)'}}><span style={{fontSize: 15, color: 'rgb(149, 165, 166)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><strong style={{fontSize: 14, fontFamily: 'Arial'}}><em style={{fontSize: 14, fontFamily: 'Arial'}}>This summary provides key points from our privacy notice, but you can find out more details about any of these topics by clicking the link following each key point or by using our table of contents below to find the section you are looking for. You can also click&nbsp;</em></strong></span></span><a style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word', color: 'rgb(206, 212, 217)'}} href="#toc" data-custom-class="link" aria-invalid="true"><span style={{fontSize: 15, fontFamily: 'Arial', wordBreak: 'break-word'}}><span style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word'}} data-custom-class="body_text"><strong style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word'}}><em style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word'}}>here</em></strong></span></span></a><span style={{fontSize: 15, color: 'rgb(149, 165, 166)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><strong style={{fontSize: 14, fontFamily: 'Arial'}}><em style={{fontSize: 14, fontFamily: 'Arial'}}>&nbsp;to go directly to our table of contents.</em></strong></span></span></span></div>
    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
    <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><span style={{color: 'rgb(149, 165, 166)'}}><strong style={{fontSize: 14, fontFamily: 'Arial'}}>What personal information do we process?</strong>&nbsp;When you visit, use, or navigate our Services, we may process personal information depending on how you interact with&nbsp;Mectra India&nbsp;and the Services, the choices you make, and the products and features you use. Click</span>&nbsp;</span></span><a style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word'}} href="#personalinfo" data-custom-class="link" aria-invalid="true"><span style={{fontSize: 15, fontFamily: 'Arial', wordBreak: 'break-word'}}><span style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word'}} data-custom-class="body_text">here</span></span></a><span style={{fontSize: 15, color: 'rgb(149, 165, 166)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">&nbsp;to learn more.</span></span></div>
    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
    <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(149, 165, 166)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><strong style={{fontSize: 14, fontFamily: 'Arial'}}>Do we process any sensitive personal information?</strong>&nbsp;We do not process sensitive personal information.</span></span></div>
    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
    <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(149, 165, 166)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><strong style={{fontSize: 14, fontFamily: 'Arial'}}>Do we receive any information from third parties?</strong>&nbsp;We do not receive any information from third parties.</span></span></div>
    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
    <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><span style={{color: 'rgb(149, 165, 166)'}}><strong style={{fontSize: 14, fontFamily: 'Arial'}}>How do we process your information?</strong>&nbsp;We process your information to provide, improve, and administer our Services, communicate with you, for security and fraud prevention, and to comply with law. We may also process your information for other purposes with your consent. We process your information only when we have a valid legal reason to do so. Click</span>&nbsp;</span></span><a style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word'}} href="#infouse" data-custom-class="link" aria-invalid="true"><span style={{fontSize: 15, fontFamily: 'Arial', wordBreak: 'break-word'}}><span style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word'}} data-custom-class="body_text">here</span></span></a><span style={{fontSize: 15}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">&nbsp;<span style={{color: 'rgb(149, 165, 166)'}}>to learn more.</span></span></span></div>
    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
    <div style={{lineHeight: '1.5'}}><span style={{color: 'rgb(149, 165, 166)'}}><span style={{fontSize: 15}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><strong style={{fontSize: 14, fontFamily: 'Arial'}}>In what situations and with which&nbsp;parties do we share personal information?</strong>&nbsp;We may share information in specific situations and with specific&nbsp;third parties. Click&nbsp;</span></span><a style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word', color: 'rgb(149, 165, 166)'}} href="#whoshare" data-custom-class="link" aria-invalid="true"><span style={{fontSize: 15, fontFamily: 'Arial', wordBreak: 'break-word'}}><span style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word'}} data-custom-class="body_text">here</span></span></a><span style={{fontSize: 15}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">&nbsp;to learn more.</span></span></span></div>
    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
    <div style={{lineHeight: '1.5'}}><span style={{color: 'rgb(149, 165, 166)'}}><span style={{fontSize: 15}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><strong style={{fontSize: 14, fontFamily: 'Arial'}}>How do we keep your information safe?</strong>&nbsp;We have&nbsp;organizational&nbsp;and technical processes and procedures in place to protect your personal information. However, no electronic transmission over the internet or information storage technology can be guaranteed to be 100% secure, so we cannot promise or guarantee that hackers, cybercriminals, or other&nbsp;unauthorized&nbsp;third parties will not be able to defeat our security and improperly collect, access, steal, or modify your information. Click&nbsp;</span></span><a style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word', color: 'rgb(149, 165, 166)'}} href="#infosafe" data-custom-class="link" aria-invalid="true"><span style={{fontSize: 15, fontFamily: 'Arial', wordBreak: 'break-word'}}><span style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word'}} data-custom-class="body_text">here</span></span></a><span style={{fontSize: 15}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">&nbsp;to learn more.</span></span></span></div>
    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
    <div style={{lineHeight: '1.5'}}><span style={{color: 'rgb(149, 165, 166)'}}><span style={{fontSize: 15}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><strong style={{fontSize: 14, fontFamily: 'Arial'}}>What are your rights?</strong>&nbsp;Depending on where you are located geographically, the applicable privacy law may mean you have certain rights regarding your personal information. Click&nbsp;</span></span><a style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word', color: 'rgb(149, 165, 166)'}} href="#privacyrights" data-custom-class="link" aria-invalid="true"><span style={{fontSize: 15, fontFamily: 'Arial', wordBreak: 'break-word'}}><span style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word'}} data-custom-class="body_text">here</span></span></a><span style={{fontSize: 15}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">&nbsp;to learn more.</span></span></span></div>
    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
    <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(149, 165, 166)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><strong style={{fontSize: 14, fontFamily: 'Arial'}}>How do I exercise my rights?</strong>&nbsp;The easiest way to exercise your rights is by filling out our data subject request form available&nbsp;here:&nbsp;mectraindia.com, or by contacting us. We will consider and act upon any request in accordance with applicable data protection laws.</span></span></div>
    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
    <div style={{lineHeight: '1.5'}}><span style={{color: 'rgb(149, 165, 166)'}}><span style={{fontSize: 15}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">Want to learn more about what&nbsp;Mectra India&nbsp;does with any information we collect? Click&nbsp;</span></span><a style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word', color: 'rgb(149, 165, 166)'}} href="#toc" data-custom-class="link" aria-invalid="true"><span style={{fontSize: 15, fontFamily: 'Arial', wordBreak: 'break-word'}}><span style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word'}} data-custom-class="body_text">here</span></span></a><span style={{fontSize: 15}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">&nbsp;to review the notice in full.</span></span></span></div>
    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
    <div id="toc" style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(206, 212, 217)'}}><strong><span style={{fontSize: 19}} data-custom-class="heading_1">TABLE OF CONTENTS</span></strong></span></div>
    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
    <div style={{lineHeight: '1.5'}}><span style={{textDecoration: 'underline'}}><em><strong><span style={{fontSize: 15}}><a style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word'}} href="#infocollect" data-custom-class="link" aria-invalid="true"><span style={{color: 'rgb(89, 89, 89)', fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word', textDecoration: 'underline'}}><span style={{color: 'rgb(206, 212, 217)', textDecoration: 'underline'}}>1. WHAT INFORMATION DO WE COLLECT?</span></span></a></span></strong></em></span></div>
    <div style={{lineHeight: '1.5'}}><span style={{textDecoration: 'underline', color: 'rgb(206, 212, 217)'}}><em><strong><span style={{fontSize: 15}}><a style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word', color: 'rgb(206, 212, 217)', textDecoration: 'underline'}} href="#infouse" data-custom-class="link" aria-invalid="true"><span style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word'}}>2. HOW DO WE PROCESS YOUR INFORMATION?</span></a></span></strong></em></span></div>
    <div style={{lineHeight: '1.5'}}><span style={{textDecoration: 'underline', color: 'rgb(206, 212, 217)'}}><em><strong><span style={{fontSize: 15}}><a style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word', color: 'rgb(206, 212, 217)', textDecoration: 'underline'}} href="#whoshare" data-custom-class="link" aria-invalid="true">3. WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?</a></span></strong></em></span></div>
    <div style={{lineHeight: '1.5'}}><span style={{textDecoration: 'underline', color: 'rgb(206, 212, 217)'}}><em><strong><span style={{fontSize: 15}}><a style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word', color: 'rgb(206, 212, 217)', textDecoration: 'underline'}} href="#inforetain" data-custom-class="link" aria-invalid="true"><span style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word'}}>4. HOW LONG DO WE KEEP YOUR INFORMATION?</span></a></span></strong></em></span></div>
    <div style={{lineHeight: '1.5'}}><span style={{textDecoration: 'underline', color: 'rgb(206, 212, 217)'}}><em><strong><span style={{fontSize: 15}}><a style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word', color: 'rgb(206, 212, 217)', textDecoration: 'underline'}} href="#infosafe" data-custom-class="link" aria-invalid="true"><span style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word'}}>5. HOW DO WE KEEP YOUR INFORMATION SAFE?</span></a></span></strong></em></span></div>
    <div style={{lineHeight: '1.5'}}><span style={{textDecoration: 'underline', color: 'rgb(206, 212, 217)'}}><em><strong><span style={{fontSize: 15}}><a style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word', color: 'rgb(206, 212, 217)', textDecoration: 'underline'}} href="#privacyrights" data-custom-class="link" aria-invalid="true">6. WHAT ARE YOUR PRIVACY RIGHTS?</a></span></strong></em></span></div>
    <div style={{lineHeight: '1.5'}}><span style={{textDecoration: 'underline', color: 'rgb(206, 212, 217)'}}><em><strong><span style={{fontSize: 15}}><a style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word', color: 'rgb(206, 212, 217)', textDecoration: 'underline'}} href="#DNT" data-custom-class="link" aria-invalid="true"><span style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word'}}>7. CONTROLS FOR DO-NOT-TRACK FEATURES</span></a></span></strong></em></span></div>
    <div style={{lineHeight: '1.5'}}><span style={{textDecoration: 'underline', color: 'rgb(206, 212, 217)'}}><em><strong><span style={{fontSize: 15}}><a style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word', color: 'rgb(206, 212, 217)', textDecoration: 'underline'}} href="#caresidents" data-custom-class="link" aria-invalid="true"><span style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word'}}>8. DO CALIFORNIA RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS?</span></a></span></strong></em></span></div>
    <div style={{lineHeight: '1.5'}}><span style={{textDecoration: 'underline', color: 'rgb(206, 212, 217)'}}><em><strong><span style={{fontSize: 15}}><a style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word', color: 'rgb(206, 212, 217)', textDecoration: 'underline'}} href="#policyupdates" data-custom-class="link" aria-invalid="true"><span style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word'}}>9. DO WE MAKE UPDATES TO THIS NOTICE?</span></a></span></strong></em></span></div>
    <div style={{lineHeight: '1.5'}}><span style={{textDecoration: 'underline', color: 'rgb(206, 212, 217)'}}><em><strong><a style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word', color: 'rgb(206, 212, 217)', textDecoration: 'underline'}} href="#contact" data-custom-class="link" aria-invalid="true"><span style={{fontSize: 15, fontFamily: 'Arial', wordBreak: 'break-word'}}>10. HOW CAN YOU CONTACT US ABOUT THIS NOTICE?</span></a></strong></em></span></div>
    <div style={{lineHeight: '1.5'}}><span style={{textDecoration: 'underline', color: 'rgb(206, 212, 217)'}}><em><strong><a style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word', color: 'rgb(206, 212, 217)', textDecoration: 'underline'}} href="#request" data-custom-class="link" aria-invalid="true"><span style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word'}}>11. HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM YOU?</span></a></strong></em></span></div>
    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
    <div id="infocollect" style={{lineHeight: '1.5'}}><span style={{color: 'rgb(206, 212, 217)'}}><span style={{fontSize: 15}}><span id="control"><strong><span style={{fontSize: 19}} data-custom-class="heading_1">1. WHAT INFORMATION DO WE COLLECT?</span></strong></span></span></span></div>
    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
    <div id="personalinfo" style={{lineHeight: '1.5'}}><span style={{color: 'rgb(149, 165, 166)', fontSize: 17}} data-custom-class="heading_2"><span style={{fontSize: 15}}><strong style={{fontSize: 17}}>Personal information you disclose to us</strong></span></span></div>
    <div>
      <div>&nbsp;</div>
      <div style={{lineHeight: '1.5'}}><span style={{color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 15}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><span style={{fontSize: 15, fontFamily: 'Arial'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><strong style={{fontSize: 14, fontFamily: 'Arial'}}><em style={{fontSize: 14, fontFamily: 'Arial'}}>In Short:</em></strong></span></span></span><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><span style={{fontSize: 15, fontFamily: 'Arial'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><strong style={{fontSize: 14, fontFamily: 'Arial'}}><em style={{fontSize: 14, fontFamily: 'Arial'}}>&nbsp;</em></strong><em style={{fontSize: 14, fontFamily: 'Arial'}}>We collect personal information that you provide to us.</em></span></span></span></span></span></div>
    </div>
    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
    <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">We collect personal information that you voluntarily provide to us when you&nbsp;</span><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">express an interest in obtaining information about us or our products and Services, when you participate in activities on the Services, or otherwise when you contact us.</span></span></div>
    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
    <div id="sensitiveinfo" style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(149, 165, 166)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><strong style={{fontSize: 14, fontFamily: 'Arial'}}>Sensitive Information.</strong>&nbsp;We do not process sensitive information.</span></span></div>
    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
    <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(149, 165, 166)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">All personal information that you provide to us must be true, complete, and accurate, and you must notify us of any changes to such personal information.</span></span></div>
    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
    <div id="infouse" style={{lineHeight: '1.5'}}><span style={{color: 'rgb(236, 240, 241)'}}><span style={{fontSize: 15}}><span id="control"><strong><span style={{fontSize: 19}} data-custom-class="heading_1">2. HOW DO WE PROCESS YOUR INFORMATION?</span></strong></span></span></span></div>
    <div>
      <div style={{lineHeight: '1.5'}}>&nbsp;</div>
      <div style={{lineHeight: '1.5'}}><span style={{color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 15}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><span style={{fontSize: 15, fontFamily: 'Arial'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><strong style={{fontSize: 14, fontFamily: 'Arial'}}><em style={{fontSize: 14, fontFamily: 'Arial'}}>In Short:&nbsp;</em></strong><em style={{fontSize: 14, fontFamily: 'Arial'}}>We process your information to provide, improve, and administer our Services, communicate with you, for security and fraud prevention, and to comply with law. We may also process your information for other purposes with your consent.</em></span></span></span></span></span></div>
    </div>
    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
    <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><strong style={{fontSize: 14, fontFamily: 'Arial'}}>We process your personal information for a variety of reasons, depending on how you interact with our Services, including:</strong></span></span>
      <div style={{lineHeight: '1.5'}}>
        <div style={{lineHeight: '1.5'}}>
          <div style={{lineHeight: '1.5'}}>
            <div style={{lineHeight: '1.5'}}>
              <div style={{lineHeight: '1.5'}}>
                <div style={{lineHeight: '1.5'}}>
                  <div style={{lineHeight: '1.5'}}>
                    <div style={{lineHeight: '1.5'}}>
                      <p style={{fontSize: 15, lineHeight: '1.5'}}>&nbsp;</p>
                      <p style={{fontSize: 15, lineHeight: '1.5'}}>&nbsp;</p>
                      <p style={{fontSize: 15, lineHeight: '1.5'}}>&nbsp;</p>
                      <p style={{fontSize: 15, lineHeight: '1.5'}}>&nbsp;</p>
                      <div style={{lineHeight: '1.5'}}>
                        <div style={{lineHeight: '1.5'}}>
                          <div style={{lineHeight: '1.5'}}>
                            <div style={{lineHeight: '1.5'}}>
                              <div style={{lineHeight: '1.5'}}>
                                <div style={{lineHeight: '1.5'}}>
                                  <div style={{lineHeight: '1.5'}}>
                                    <div style={{lineHeight: '1.5'}}>
                                      <div style={{lineHeight: '1.5'}}>
                                        <div style={{lineHeight: '1.5'}}>
                                          <div style={{lineHeight: '1.5'}}>
                                            <div style={{lineHeight: '1.5'}}>
                                              <div style={{lineHeight: '1.5'}}>
                                                <div style={{lineHeight: '1.5'}}>
                                                  <div style={{lineHeight: '1.5'}}>
                                                    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                    <div id="whoshare" style={{lineHeight: '1.5'}}><span style={{color: 'rgb(206, 212, 217)'}}><span style={{fontSize: 15}}><span id="control"><strong><span style={{fontSize: 19}} data-custom-class="heading_1">3. WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?</span></strong></span></span></span></div>
                                                    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                    <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><strong style={{fontSize: 14, fontFamily: 'Arial'}}><em style={{fontSize: 14, fontFamily: 'Arial'}}>In Short:</em></strong><em style={{fontSize: 14, fontFamily: 'Arial'}}>&nbsp;We may share information in specific situations described in this section and/or with the following&nbsp;third parties.</em></span></span></div>
                                                    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                    <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                    <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(149, 165, 166)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">We&nbsp;may need to share your personal information in the following situations:</span></span></div>
                                                    <ul>
                                                      <li style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(149, 165, 166)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><strong style={{fontSize: 14, fontFamily: 'Arial'}}>Business Transfers.</strong>&nbsp;We may share or transfer your information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company.</span></span></li>
                                                    </ul>
                                                    <div style={{lineHeight: '1.5'}}>
                                                      <div style={{lineHeight: '1.5'}}>
                                                        <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                        <ul>
                                                          <li style={{lineHeight: '1.5'}}><span style={{fontSize: 14, fontFamily: 'Arial', color: 'rgb(149, 165, 166)'}} data-custom-class="body_text"><span style={{fontSize: 15, fontFamily: 'Arial'}}><strong style={{fontSize: 14, fontFamily: 'Arial'}}>Business Partners.</strong>&nbsp;We may share your information with our business partners to offer you certain products, services, or promotions.</span></span></li>
                                                        </ul>
                                                        <div style={{lineHeight: '1.5'}}>
                                                          <div style={{lineHeight: '1.5'}}>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div id="inforetain" style={{lineHeight: '1.5'}}><span style={{color: 'rgb(206, 212, 217)'}}><span style={{fontSize: 15}}><span id="control"><strong><span style={{fontSize: 19}} data-custom-class="heading_1">4. HOW LONG DO WE KEEP YOUR INFORMATION?</span></strong></span></span></span></div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><strong style={{fontSize: 14, fontFamily: 'Arial'}}><em style={{fontSize: 14, fontFamily: 'Arial'}}>In Short:&nbsp;</em></strong><em style={{fontSize: 14, fontFamily: 'Arial'}}>We keep your information for as long as necessary to&nbsp;fulfill&nbsp;the purposes outlined in this privacy notice unless otherwise required by law.</em></span></span></div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">We will only keep your personal information for as long as it is necessary for the purposes set out in this privacy notice, unless a longer retention period is required or permitted by law (such as tax, accounting, or other legal requirements). No purpose in this notice will require us keeping your personal information for longer than&nbsp;<span style={{fontSize: 15, fontFamily: 'Arial'}}><span style={{fontSize: 14, fontFamily: 'Arial'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">__________</span></span></span>.</span></span></div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">When we have no ongoing legitimate business need to process your personal information, we will either delete or&nbsp;anonymize&nbsp;such information, or, if this is not possible (for example, because your personal information has been stored in backup archives), then we will securely store your personal information and isolate it from any further processing until deletion is possible.</span></span></div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div id="infosafe" style={{lineHeight: '1.5'}}><span style={{color: 'rgb(206, 212, 217)'}}><span style={{fontSize: 15}}><span id="control"><strong><span style={{fontSize: 19}} data-custom-class="heading_1">5. HOW DO WE KEEP YOUR INFORMATION SAFE?</span></strong></span></span></span></div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><strong style={{fontSize: 14, fontFamily: 'Arial'}}><em style={{fontSize: 14, fontFamily: 'Arial'}}>In Short:&nbsp;</em></strong><em style={{fontSize: 14, fontFamily: 'Arial'}}>We aim to protect your personal information through a system of&nbsp;organizational&nbsp;and technical security measures.</em></span></span></div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">We have implemented appropriate and reasonable technical and&nbsp;organizational&nbsp;security measures designed to protect the security of any personal information we process. However, despite our safeguards and efforts to secure your information, no electronic transmission over the Internet or information storage technology can be guaranteed to be 100% secure, so we cannot promise or guarantee that hackers, cybercriminals, or other&nbsp;unauthorized&nbsp;third parties will not be able to defeat our security and improperly collect, access, steal, or modify your information. Although we will do our best to protect your personal information, transmission of personal information to and from our Services is at your own risk. You should only access the Services within a secure environment.</span></span></div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div id="privacyrights" style={{lineHeight: '1.5'}}><span style={{color: 'rgb(206, 212, 217)'}}><span style={{fontSize: 15}}><span id="control"><strong><span style={{fontSize: 19}} data-custom-class="heading_1">6. WHAT ARE YOUR PRIVACY RIGHTS?</span></strong></span></span></span></div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><strong style={{fontSize: 14, fontFamily: 'Arial'}}><em style={{fontSize: 14, fontFamily: 'Arial'}}>In Short:</em></strong><em style={{fontSize: 14, fontFamily: 'Arial'}}>&nbsp;<span style={{fontSize: 14, fontFamily: 'Arial'}}>&nbsp;</span>You may review, change, or terminate your account at any time.</em></span></span></div>
                                                            <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(198, 198, 198)'}}>&nbsp;</span></div>
                                                            <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(89, 89, 89)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><span style={{color: 'rgb(198, 198, 198)'}}>If you are located in the EEA or UK and you believe we are unlawfully processing your personal information, you also have the right to complain to your local data protection supervisory authority. You can find their contact details here:</span>&nbsp;<span style={{fontSize: 15, fontFamily: 'Arial'}}><span style={{color: 'rgb(89, 89, 89)', fontSize: 14, fontFamily: 'Arial'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><span style={{color: 'rgb(48, 48, 241)', fontSize: 14, fontFamily: 'Arial'}}><a style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word'}} href="https://ec.europa.eu/justice/data-protection/bodies/authorities/index_en.htm" target="_blank" rel="noopener noreferrer" data-custom-class="link"><span style={{fontSize: 15, fontFamily: 'Arial', wordBreak: 'break-word'}}>https://ec.europa.eu/justice/data-protection/bodies/authorities/index_en.htm</span></a></span></span></span></span>.</span></span></div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(89, 89, 89)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><span style={{color: 'rgb(198, 198, 198)'}}>If you are located in Switzerland, the contact details for the data protection authorities are available here:</span>&nbsp;<span style={{fontSize: 15, fontFamily: 'Arial'}}><span style={{color: 'rgb(89, 89, 89)', fontSize: 14, fontFamily: 'Arial'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><span style={{color: 'rgb(48, 48, 241)', fontSize: 14, fontFamily: 'Arial'}}><span style={{fontSize: 15, fontFamily: 'Arial'}}><a style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word'}} href="https://www.edoeb.admin.ch/edoeb/en/home.html" target="_blank" rel="noopener noreferrer" data-custom-class="link">https://www.edoeb.admin.ch/edoeb/en/home.html</a></span></span></span></span></span>.</span></span></div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div id="withdrawconsent" style={{lineHeight: '1.5'}}><span style={{color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 15}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><strong style={{fontSize: 14, fontFamily: 'Arial'}}><span style={{fontSize: 14, fontFamily: 'Arial'}}>Withdrawing your consent:</span></strong>&nbsp;If we are relying on your consent to process your personal information,&nbsp;which may be express and/or implied consent depending on the applicable law,&nbsp;you have the right to withdraw your consent at any time. You can withdraw your consent at any time by contacting us by using the contact details provided in the section&nbsp;&quot;</span></span><a style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word', color: 'rgb(198, 198, 198)'}} href="#contact" data-custom-class="link" aria-invalid="true"><span style={{fontSize: 15, fontFamily: 'Arial', wordBreak: 'break-word'}}><span style={{fontSize: 14, fontFamily: 'Arial', wordBreak: 'break-word'}} data-custom-class="body_text">HOW CAN YOU CONTACT US ABOUT THIS NOTICE?</span></span></a><span style={{fontSize: 15}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">&quot;&nbsp;below.</span></span></span></div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">However, please note that this will not affect the lawfulness of the processing before its withdrawal, nor&nbsp;when applicable law allows,&nbsp;will it affect the processing of your personal information conducted in reliance on lawful processing grounds other than consent.</span></span></div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div style={{lineHeight: '1.5'}}><span style={{fontSize: 14, fontFamily: 'Arial', color: 'rgb(198, 198, 198)'}} data-custom-class="body_text"><span style={{fontSize: 15, fontFamily: 'Arial'}}>If you have questions or comments about your privacy rights, you may email us at&nbsp;support@mectraindia.com.</span></span></div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div id="DNT" style={{lineHeight: '1.5'}}><span style={{color: 'rgb(206, 212, 217)'}}><span style={{fontSize: 15}}><span id="control"><strong><span style={{fontSize: 19}} data-custom-class="heading_1">7. CONTROLS FOR DO-NOT-TRACK FEATURES</span></strong></span></span></span></div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">Most web browsers and some mobile operating systems and mobile applications include a Do-Not-Track (&quot;DNT&quot;) feature or setting you can activate to signal your privacy preference not to have data about your online browsing activities monitored and collected. At this stage no uniform technology standard for&nbsp;recognizing&nbsp;and implementing DNT signals has been&nbsp;finalized. As such, we do not currently respond to DNT browser signals or any other mechanism that automatically communicates your choice not to be tracked online. If a standard for online tracking is adopted that we must follow in the future, we will inform you about that practice in a revised version of this privacy notice.</span></span></div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div id="caresidents" style={{lineHeight: '1.5'}}><span style={{color: 'rgb(206, 212, 217)'}}><span style={{fontSize: 15}}><span id="control"><strong><span style={{fontSize: 19}} data-custom-class="heading_1">8. DO CALIFORNIA RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS?</span></strong></span></span></span></div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><strong style={{fontSize: 14, fontFamily: 'Arial'}}><em style={{fontSize: 14, fontFamily: 'Arial'}}>In Short:&nbsp;</em></strong><em style={{fontSize: 14, fontFamily: 'Arial'}}>Yes, if you are a resident of California, you are granted specific rights regarding access to your personal information.</em></span></span></div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">California Civil Code Section 1798.83, also known as the&nbsp;&quot;Shine The Light&quot;&nbsp;law, permits our users who are California residents to request and obtain from us, once a year and free of charge, information about categories of personal information (if any) we disclosed to third parties for direct marketing purposes and the names and addresses of all third parties with which we shared personal information in the immediately preceding calendar year. If you are a California resident and would like to make such a request, please submit your request in writing to us using the contact information provided below.</span></span></div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">If you are under 18 years of age, reside in California, and have a registered account with Services, you have the right to request removal of unwanted data that you publicly post on the Services. To request removal of such data, please contact us using the contact information provided below and include the email address associated with your account and a statement that you reside in California. We will make sure the data is not publicly displayed on the Services, but please be aware that the data may not be completely or comprehensively removed from all our systems (e.g.,&nbsp;backups, etc.).</span></span></div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div id="policyupdates" style={{lineHeight: '1.5'}}><span style={{color: 'rgb(206, 212, 217)'}}><span style={{fontSize: 15}}><span id="control"><strong><span style={{fontSize: 19}} data-custom-class="heading_1">9. DO WE MAKE UPDATES TO THIS NOTICE?</span></strong></span></span></span></div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><em style={{fontSize: 14, fontFamily: 'Arial'}}><strong style={{fontSize: 14, fontFamily: 'Arial'}}>In Short:&nbsp;</strong>Yes, we will update this notice as necessary to stay compliant with relevant laws.</em></span></span></div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">We may update this privacy notice from time to time. The updated version will be indicated by an updated&nbsp;&quot;Revised&quot;&nbsp;date and the updated version will be effective as soon as it is accessible. If we make material changes to this privacy notice, we may notify you either by prominently posting a notice of such changes or by directly sending you a notification. We encourage you to review this privacy notice frequently to be informed of how we are protecting your information.</span></span></div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div id="contact" style={{lineHeight: '1.5'}}><span style={{color: 'rgb(206, 212, 217)'}}><span style={{fontSize: 15}}><span id="control"><strong><span style={{fontSize: 19}} data-custom-class="heading_1">10. HOW CAN YOU CONTACT US ABOUT THIS NOTICE?</span></strong></span></span></span></div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">If you have questions or <span style={{color: 'rgb(206, 212, 217)'}}>comments</span> about this notice, you may&nbsp;<span style={{fontSize: 15, fontFamily: 'Arial'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">email us at support@mectraindia.com</span></span><span style={{fontSize: 15, fontFamily: 'Arial'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">&nbsp;or by post to:</span></span></span></span></div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text"><span style={{fontSize: 15, fontFamily: 'Arial'}}><span style={{fontSize: 14, fontFamily: 'Arial'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">Mectra India</span></span></span></span></span></div>
                                                            <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">Gurugram, Haryana</span></span></div>
                                                            <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, fontFamily: 'Arial', color: 'rgb(198, 198, 198)'}} data-custom-class="body_text">Gurugram, Haryana</span></div>
                                                            <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">Gurugram<span style={{fontSize: 14, fontFamily: 'Arial'}}><span style={{fontSize: 15, fontFamily: 'Arial'}}>,&nbsp;Haryana&nbsp;110038</span></span></span></span></div>
                                                            <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">India</span></span></div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div id="request" style={{lineHeight: '1.5'}}><span style={{color: 'rgb(206, 212, 217)'}}><span style={{fontSize: 15}}><span id="control"><strong><span style={{fontSize: 19}} data-custom-class="heading_1">11. HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM YOU?</span></strong></span></span></span></div>
                                                            <div style={{lineHeight: '1.5'}}>&nbsp;</div>
                                                            <div style={{lineHeight: '1.5'}}><span style={{fontSize: 15, color: 'rgb(198, 198, 198)'}}><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">Based on the applicable laws of your country, you may have the right to request access to the personal information we collect from you, change that information, or delete it in some circumstances. To request to review, update, or delete your personal information, please&nbsp;</span><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">visit:&nbsp;mectraindia.com</span><span style={{fontSize: 14, fontFamily: 'Arial'}} data-custom-class="body_text">.</span></span></div>
                                                          </div>
                                                        </div>
                                                      </div>
                                                    </div>
                                                  </div>
                                                </div>
                                              </div>
                                            </div>
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


    )
}

export default privacy